/**
 * 应用中用到的所有action常量集合
 */

const TYPES = {
    TO_LOGIN: "TO_LOGIN",
    TO_REGISTER: "TO_REGISTER",
    SHOW_SEARCH_MODAL: "SHOW_SEARCH_MODAL",
    CLOSE_SEARCH_MODAL: "CLOSE_SEARCH_MODAL",
    REQUEST_START: "REQUEST_START",
    REQUEST_ERR: "REQUEST_ERR",
    REQUEST_SUCCESS: "REQUEST_SUCCESS",
}

export default TYPES;